name: Update shops.json

on:
  schedule:
    - cron: '0 2 * * *'   # svaki dan u 02:00 UTC (promeni po potrebi)
  workflow_dispatch:      # manualno pokretanje iz Actions taba

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run fetch script
        run: npm run fetch

      - name: Commit updated shops.json (if changed)
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'chore: update shops.json'
          add: 'public/shops.json'
          push: true
